version: '3.7'
services:
  # postgres db server
  db:
    image: postgres:13.10-alpine #per Mark K this is the version we should be running
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging: &loggingLocal
      driver: local
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      network:
        ipv4_address: 10.5.0.4
  # browser admin tool
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@torch.ai
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - '15432:80'
    networks:
      network:
        ipv4_address: 10.5.0.5
    logging: &loggingLocal
      driver: local
volumes:
  db:
    driver: local
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
